# permissions for end users to view matanapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: matanmagen-crd
    app.kubernetes.io/managed-by: kustomize
  name: matanapp-viewer-role
rules:
- apiGroups:
  - api.core.matanmagen.io
  resources:
  - matanapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.core.matanmagen.io
  resources:
  - matanapps/status
  verbs:
  - get
